version: "3.8"

services:
  db:
    container_name: one_for_all_db
    image: mysql:8.0.36
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password


networks:
  default:
    name: one_for_all_net